# Generated by Django 5.0.6 on 2024-05-28 16:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalystcountapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("industry", models.CharField(max_length=255)),
                ("year_founded", models.IntegerField(blank=True, null=True)),
                ("city", models.CharField(max_length=255)),
                ("state", models.CharField(max_length=255)),
                ("country", models.CharField(max_length=255)),
                ("employees", models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
